# Generated by Django 4.0.2 on 2022-03-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='mobile_no',
            field=models.CharField(max_length=15),
        ),
    ]
